name: mosques_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.8.0

dependencies:
  adhan_dart: ^1.2.0
  arabic_search: ^0.2.3
  dartz: ^0.10.1
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_nav_bar: ^5.0.7
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.12.4
  url_launcher: ^6.3.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  flutter_timezone: ^4.1.0
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
